import { apiClient } from './api'
import type {
  DeliverableItem,
  DeliverableFilterParams,
  DeliverableAuditTrail,
} from '@/types/deliverable'

/**
 * Zenith AI — Sovereign Deliverables Service Abstraction
 *
 * Manages certified outputs generated by autonomous workflow pipelines.
 */

let mockDeliverables: DeliverableItem[] = [
  {
    id: 'DEL-801',
    filename: 'Turbine_Blade_Thermal_Stress_Certified_Report.pdf',
    fileType: 'PDF',
    workflow: 'Inspection Report → Approval Note',
    workflowId: 'wf-01',
    generatedBy: 'Ravi (Chief Eng)',
    createdDate: '2026-09-02 14:35',
    sizeBytes: 15518924, // 14.8 MB
    formattedSize: '14.8 MB',
    verificationStatus: 'VERIFIED',
    checksumSha256: '8f4ad91ce7a328109bfbc42298fc1c149afbf4c8996fb92427ae41e4649b934c',
    hsmAttestation: 'HSM-YUBI-FIPS-LVL3-09412',
    auditTrailId: 'AUD-9014',
    previewContent: `### ZENITH SOVEREIGN DELIVERABLE ATTESTATION
Document: Turbine_Blade_Thermal_Stress_Certified_Report.pdf
Workflow: Inspection Report → Approval Note (ID: wf-01)
Hash: 8f4ad91ce7a328109bfbc42298fc1c149afbf4c8996fb92427ae41e4649b934c

1. EXECUTIVE COMPLIANCE DISPOSITION
All multi-physics Von Mises stress nodes evaluated against ISO 1982 Section 4.8.2.
- Peak Root Stress: 542.80 MPa
- Material Yield Limit: 680.00 MPa
- Computed Safety Factor: 1.25x (Pass Threshold >= 1.15x)
Status: DISPOSITION APPROVED FOR AEROSPACE OVERHAUL`,
  },
  {
    id: 'DEL-802',
    filename: 'Executive_Engineering_Approval_Note.docx',
    fileType: 'DOCX',
    workflow: 'Inspection Report → Approval Note',
    workflowId: 'wf-01',
    generatedBy: 'Ravi (Chief Eng)',
    createdDate: '2026-09-02 14:36',
    sizeBytes: 2516582, // 2.4 MB
    formattedSize: '2.4 MB',
    verificationStatus: 'VERIFIED',
    checksumSha256: '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08',
    hsmAttestation: 'HSM-YUBI-FIPS-LVL3-09412',
    auditTrailId: 'AUD-9015',
    previewContent: `EXECUTIVE APPROVAL NOTE // SOVEREIGN ENCLAVE RELEASE
Prepared For: Chief Engineer & Quality Directorate
Subject: Stage 1 Inconel 718 Turbine Rotor Blade Ingestion

The autonomous pipeline has validated dimensional tolerances and thermal expansion coefficients. Formal authorization is granted to proceed with hot-section assembly.`,
  },
  {
    id: 'DEL-803',
    filename: 'SCADA_Pump_Telemetry_Statistical_Summary.xlsx',
    fileType: 'XLSX',
    workflow: 'Spreadsheet Analysis',
    workflowId: 'wf-04',
    generatedBy: 'Sarah Connor',
    createdDate: '2026-09-02 11:20',
    sizeBytes: 6710886, // 6.4 MB
    formattedSize: '6.4 MB',
    verificationStatus: 'VERIFIED',
    checksumSha256: '6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b',
    hsmAttestation: 'HSM-YUBI-FIPS-LVL3-08819',
    auditTrailId: 'AUD-9008',
    previewContent: `Telemetry Statistical Summary (XLSX Workbook)
Sheets: Raw_Sensor_100Hz, Anomaly_Clustering, FFT_Spectral_Peaks
Total Data Points: 1,480,200
Verified Clean Cells: 100.0%
Standard Deviation: 1.42 bar (Within +/- 3.0 sigma operating threshold)`,
  },
  {
    id: 'DEL-804',
    filename: 'Aero_Engine_Thermal_Architecture_Brief.pptx',
    fileType: 'PPTX',
    workflow: 'Document Intelligence',
    workflowId: 'wf-03',
    generatedBy: 'Elena Vance',
    createdDate: '2026-09-01 16:40',
    sizeBytes: 31457280, // 30.0 MB
    formattedSize: '30.0 MB',
    verificationStatus: 'PENDING_REVIEW',
    checksumSha256: 'd4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f90da3a666eec13ab35',
    hsmAttestation: 'HSM-YUBI-FIPS-LVL3-07114',
    auditTrailId: 'AUD-8942',
    previewContent: `Technical Architecture Slides (PPTX)
Slides: 34
Topic: High-Pressure Combustor Film Cooling & Thermal Barrier Coating
Review Status: Awaiting independent verification by Auditor before flight clearance certification.`,
  },
  {
    id: 'DEL-805',
    filename: 'IEC61131_TwinCAT3_Verified_Interlock_Block.code',
    fileType: 'CODE',
    workflow: 'Coding Verification',
    workflowId: 'wf-02',
    generatedBy: 'Kai Chen',
    createdDate: '2026-09-01 09:15',
    sizeBytes: 384120, // 375 KB
    formattedSize: '375 KB',
    verificationStatus: 'VERIFIED',
    checksumSha256: 'ef2d127de37b942baad06145e54b0c619a1f22327b2ebbcfbec78f5564afe39d',
    hsmAttestation: 'HSM-YUBI-FIPS-LVL3-08819',
    auditTrailId: 'AUD-8910',
    previewContent: `(* ========================================================= *)
(* BECKHOFF TWINCAT 3 STRUCTURED TEXT - VERIFIED INTERLOCK   *)
(* Formal Model: FIPS-Verified Zero Deadlock State Machine   *)
(* ========================================================= *)
FUNCTION_BLOCK FB_EmergencyCoolantInterlock
VAR_INPUT
    bSensorHighTempAlarm : BOOL;
    rDifferentialPressureBar : REAL;
    bManualOverrideEnable : BOOL;
END_VAR
VAR_OUTPUT
    bTripPneumaticValve : BOOL;
    bAuxiliaryBypassEngaged : BOOL;
    eInterlockState : E_SafetyState;
END_VAR
// Verification Assertion Confirmed: Execution cycle latency <= 800us`,
  },
  {
    id: 'DEL-806',
    filename: 'NDT_Surface_Optical_Scan_Package.zip',
    fileType: 'ZIP',
    workflow: 'Engineering Image Analysis',
    workflowId: 'wf-05',
    generatedBy: 'Ravi (Chief Eng)',
    createdDate: '2026-08-31 18:22',
    sizeBytes: 94371840, // 90.0 MB
    formattedSize: '90.0 MB',
    verificationStatus: 'VERIFIED',
    checksumSha256: '4e07408562bedb8b60ce05c1decfe3ad16b72230967de01f640b7e4729b49fce',
    hsmAttestation: 'HSM-YUBI-FIPS-LVL3-09412',
    auditTrailId: 'AUD-8850',
    previewContent: `ZIP Archive Manifest:
- /images/dye_penetrant_fillet_01.tiff (16-bit uncompressed)
- /images/dye_penetrant_fillet_02.tiff (16-bit uncompressed)
- /masks/detected_micro_cracks.png (Binary segmentation mask)
- /metadata/radiographic_sensor_calibration.json`,
  },
  {
    id: 'DEL-807',
    filename: 'ISO_1982_Compliance_Matrix_Draft.docx',
    fileType: 'DOCX',
    workflow: 'Document Intelligence',
    workflowId: 'wf-03',
    generatedBy: 'Marcus Holt',
    createdDate: '2026-08-30 14:10',
    sizeBytes: 1887436, // 1.8 MB
    formattedSize: '1.8 MB',
    verificationStatus: 'UNVERIFIED',
    checksumSha256: '4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328cb08b5531fcacdabf8a',
    hsmAttestation: 'HSM-PENDING',
    auditTrailId: 'AUD-8802',
    previewContent: `DRAFT COMPLIANCE TRACEABILITY MATRIX
ISO 1982 Clauses 1.1 through 9.4
Status: Working draft. Formal cryptographic signing pending auditor attestation review.`,
  },
  {
    id: 'DEL-808',
    filename: 'FEA_Thermal_Mesh_Numerical_Solver.code',
    fileType: 'CODE',
    workflow: 'Coding Verification',
    workflowId: 'wf-02',
    generatedBy: 'Kai Chen',
    createdDate: '2026-08-29 11:05',
    sizeBytes: 819200, // 800 KB
    formattedSize: '800 KB',
    verificationStatus: 'VERIFIED',
    checksumSha256: 'e7f6c011776e8db7cd330b54174fd76f7d0216b612387a5ffcfb81e6f0919683',
    hsmAttestation: 'HSM-YUBI-FIPS-LVL3-08819',
    auditTrailId: 'AUD-8744',
    previewContent: `import numpy as np
import scipy.sparse as sp
from scipy.sparse.linalg import spsolve

def solve_3d_thermal_field(nodes: np.ndarray, elements: np.ndarray, k_thermal: float) -> np.ndarray:
    """Solves steady-state 3D Laplace heat conduction with boundary flux."""
    # Sovereign Verified Matrix Assembler
    pass`,
  },
]

export const deliverableApi = {
  /**
   * List deliverables with filtering and search
   */
  async getDeliverables(params?: DeliverableFilterParams): Promise<DeliverableItem[]> {
    try {
      const response = await apiClient.get<DeliverableItem[]>('/deliverables', { params })
      return response.data
    } catch {
      await new Promise((r) => setTimeout(r, 200))
      let list = [...mockDeliverables]

      if (params?.query) {
        const q = params.query.toLowerCase()
        list = list.filter(
          (d) =>
            d.filename.toLowerCase().includes(q) ||
            d.workflow.toLowerCase().includes(q) ||
            d.generatedBy.toLowerCase().includes(q) ||
            d.checksumSha256.toLowerCase().includes(q)
        )
      }

      if (params?.type && params.type !== 'ALL') {
        list = list.filter((d) => d.fileType === params.type)
      }

      if (params?.workflow && params.workflow !== 'ALL') {
        list = list.filter((d) => d.workflow === params.workflow)
      }

      if (params?.status && params.status !== 'ALL') {
        list = list.filter((d) => d.verificationStatus === params.status)
      }

      return list
    }
  },

  /**
   * Rename a deliverable file
   */
  async renameDeliverable(id: string, newName: string): Promise<DeliverableItem> {
    await new Promise((r) => setTimeout(r, 250))
    const item = mockDeliverables.find((d) => d.id === id)
    if (!item) throw new Error(`Deliverable ${id} not found`)

    item.filename = newName
    return { ...item }
  },

  /**
   * Delete a deliverable file
   */
  async deleteDeliverable(id: string): Promise<void> {
    await new Promise((r) => setTimeout(r, 200))
    mockDeliverables = mockDeliverables.filter((d) => d.id !== id)
  },

  /**
   * Download deliverable binary
   */
  async downloadDeliverable(id: string): Promise<Blob> {
    await new Promise((r) => setTimeout(r, 150))
    const item = mockDeliverables.find((d) => d.id === id)
    return new Blob([`Sovereign Deliverable Binary: ${item?.filename || id}`], {
      type: 'application/octet-stream',
    })
  },

  /**
   * Get cryptographic audit trail
   */
  async getAuditTrail(deliverableId: string): Promise<DeliverableAuditTrail> {
    await new Promise((r) => setTimeout(r, 150))
    const item = mockDeliverables.find((d) => d.id === deliverableId)
    if (!item) throw new Error(`Deliverable ${deliverableId} not found`)

    return {
      id: item.auditTrailId,
      deliverableId: item.id,
      filename: item.filename,
      timestamp: item.createdDate,
      actor: item.generatedBy,
      enclaveId: 'ENCLAVE-NODE-SEC-01',
      hsmSignature: item.hsmAttestation,
      checksumSha256: item.checksumSha256,
      verificationResult: item.verificationStatus === 'VERIFIED' ? 'FIPS 140-3 PASS' : 'PENDING',
      ledgerBlock: `BLOCK-#${Math.floor(Math.random() * 80000 + 120000)}`,
      policyVersion: 'SOVEREIGN-AUDIT-v2.4',
    }
  },
}
